## 1.Split this string

In [2]:
str="Hi how are you"
print(str.split())

['Hi', 'how', 'are', 'you']


## 2.Use .format() to prnt the following string bold text

In [3]:
planet="Earth"
diameter=12742
a="The diameter of{planet}is{diameter}kilometers"
print(a.format(planet="Earth",diameter=12472))

The diameter ofEarthis12472kilometers


## 3.In this nest dictionary grab the word "hello"

In [5]:
d={'k1':[1,2,3,{'nicky':['oh','women','inception',{'target':[1,2,3,'hello']}]}]}
print(d)

{'k1': [1, 2, 3, {'nicky': ['oh', 'women', 'inception', {'target': [1, 2, 3, 'hello']}]}]}


## 4.Numpy

## 4.1 Create an array of 10 zeros?

In [6]:
import numpy as np
c=np.zeros(10)*0
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4.2 Create an array of 10 fives?

In [8]:
c=np.ones(10)*5
print(c)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 25 to 40

In [9]:
arr=np.arange(25,40,2)
print(arr)

[25 27 29 31 33 35 37 39]


## 6. Create a 3*3 matrix with values ranging from 0 to 8

In [10]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate x and y

In [11]:
ar1=np.array([0,1,2])
ar2=np.array([3,4,5])
ar=np.concatenate((ar1,ar2))
print(ar)

[0 1 2 3 4 5]


## Pandas

## 8. Create a dataframe with 4 rows and 3 columns

In [13]:
import pandas as pd
data=[{'x':11,'y':40},{'x':50,'y':20},{'x':70,'y':65}]
df=pd.DataFrame(data)
print(df)

    x   y
0  11  40
1  50  20
2  70  65


In [15]:
c=pd.date_range(start='1/1/2023',end='15/2/2023')
print(c)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
               '2023-02-14', '2023-02-15'],
              dtype='datetime64[ns]', freq='D')


## 10. Create a 2D list to DataFrame

In [16]:
lt=[[1,'aa',22],[2,'bb',24],[3,'cc',23]]
df=pd.DataFrame(lt)
print(df)

   0   1   2
0  1  aa  22
1  2  bb  24
2  3  cc  23
